image: barichello/godot-ci:3.1.1

stages:
  - export
  - deploy

before_script:
  - mkdir -v -p build/linux
  - mkdir -v -p build/windows
  - mkdir -v -p build/mac
  - mkdir -v -p build/web

linux:
  stage: export
  script:
    - godot -v --export "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
    - tar czf linux.tar.gz ./build/linux/
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - linux.tar.gz